#!/bin/bash
<<+
Luca Spanedda's OS main configuration script

start the script with the following command for report:
$ bash osmainconfig | tee report.txt

# redirect stdout/stderr to a file
# exec > report.txt 2>&1 
+

echo "						"   
echo "						"   
echo "       .   *    ..            '		"
echo "              *          .		"
echo "                   *       '		"
echo "              *                *		"
echo "      *      *        *            	"
echo "              				"
echo "		.    *    .      *  .  .	"
echo "   *   '*		.    *    .      *  	"
echo "           *				"
echo "               *'				"
echo "    .    *    .      *  .  .            	"
echo "              '				"
echo "                   *'  .   *    ..	"
echo "        .   *    .	      		"
echo "						"     
echo "						"                   
echo "	personal script for all the software" 
echo "		installations and configurations" 
echo "						"   
echo "						"   

# start here

# sudo update and upgrade
sudo apt-get update && sudo apt-get upgrade -y

# git
sudo apt-get install git -y

# curl 
sudo apt-get install curl -y

# desktop app icons
sudo apt install gnome-shell-extension-manager -y
# desktop windows resize
sudo apt-get install compizconfig-settings-manager -y

# snap store
sudo snap install snap-store 

# chrome - and install wget
sudo apt install wget
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo apt install ./google-chrome-stable_current_amd64.deb

# zoom
sudo snap install zoom-client 

# python
sudo apt-get install python3 -y
sudo apt install python3-pip -y
pip install numpy
pip install scipy
pip install -U matplotlib
sudo apt-get install python3-matplotlib -y

# pure data
sudo add-apt-repository ppa:pure-data/pure-data -y
sudo apt update
sudo apt install puredata -y

# faust
sudo apt-get install faust

# LaTex
sudo apt-get install texlive-full -y

# texmaker
sudo apt-get install texmaker -y

# zotero
sudo snap install zotero-snap

# lilypond
sudo apt-get install lilypond -y

# frescobaldi

# inkscape
sudo add-apt-repository universe
sudo add-apt-repository ppa:inkscape.dev/stable
sudo apt-get update
sudo apt install inkscape

# audio from youtube app	
sudo apt-get install youtube-dl -y
# and spotify
pip install spotdl
sudo apt install ffmpeg
# bandcamp
pip3 install bandcamp-downloader
# soundcloud
pip3 install scdl --upgrade

# visual studio code
sudo apt install software-properties-common apt-transport-https wget -y
wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" -y
sudo apt install code

# Discord
sudo snap install discord -y

# Audacity
sudo add-apt-repository ppa:ubuntuhandbook1/audacity -y
sudo apt-get install audacity -y

<<++
# Pure Data Scripts for start and stop
cd ~
cat > startpdaudio <<EOF
#!/bin/bash
pacmd load-module module-jack-source channels=2; pacmd load-module module-jack-sink channels=2;
EOF
sudo chmod +x startpdaudio

cat > killpdaudio <<EOF
#!/bin/bash
killall jackd
killall pulseaudio
EOF
sudo chmod +x killpdaudio
++

# download Github User repo
mkdir Gitrepo
cd Gitrepo
mkdir LucaSpanedda
cd LucaSpanedda
sudo curl -s https://api.github.com/users/LucaSpanedda/repos | grep \"clone_url\" | awk '{print $2}' | sed -e 's/"//g' -e 's/,//g' | xargs -n1 git clone
cd ..
cd ..
echo repositories downloaded



# Reaper
sudo apt-get install build-essential libgtk-3-dev git -y
wget https://www.reaper.fm/files/6.x/reaper671_linux_x86_64.tar.xz
tar xvf reaper671_linux_x86_64.tar.xz
mkdir -p ~/reaper
mv reaper_linux_x86_64/ ~/reaper/
cd ~
git clone http://www-dev.cockos.com/wdl/WDL.git WDL/
cd ~/WDL/WDL/swell
make
ln -sf `pwd`/libSwell.so ~/reaper/reaper_linux_x86_64/REAPER/libSwell.so
cd ~/reaper/reaper_linux_x86_64
sudo bash install-reaper.sh

# pulseaudio jack
sudo apt-get install pulseaudio-module-jack
sudo apt-get install jackd -y

# end here

echo "						"   
echo "						"   
echo "       .   *    ..            '		"
echo "              *          .		"
echo "                   *       '		"
echo "              *                *		"
echo "      *      *        *            	"
echo "              				"
echo "		.    *    .      *  .  .	"
echo "   *   '*		.    *    .      *  	"
echo "           *				"
echo "               *'				"
echo "    .    *    .      *  .  .            	"
echo "              '				"
echo "                   *'  .   *    ..	"
echo "        .   *    .	      		"
echo "						"   
echo "						"     
echo "all done! - see report.txt for more info -" 
echo "						"   
echo "						"   
